name: Dynamiccheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2    
    - name: apt install dependency
      run: 
         sudo apt-get update -y install valgrind
    - name: Dynamic Analysis
      run: make dynamiccheck -C 3_Implementation/src

